# Generated by Django 4.2.26 on 2025-11-16 03:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Accounting Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('changes_made', models.BooleanField(default=False)),
                ('file_name_string', models.CharField(blank=True, max_length=500)),
                ('list_number', models.IntegerField(blank=True, null=True)),
                ('current_sequence_number', models.IntegerField(default=0)),
                ('is_copy', models.BooleanField(default=False)),
                ('is_whatif', models.BooleanField(default=False)),
                ('accounting_categories', models.ManyToManyField(blank=True, to='budgets.accountingcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unique_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('sequence_number', models.IntegerField()),
                ('monitary_value', models.DecimalField(decimal_places=2, help_text='Positive for income, negative for expenses', max_digits=12)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField(db_index=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('short_date', models.CharField(blank=True, max_length=50)),
                ('running_balance', models.DecimalField(decimal_places=2, default=0, help_text='Running balance after this transaction', max_digits=12)),
                ('import_source', models.CharField(blank=True, max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('update_timestamp', models.DateTimeField(auto_now=True)),
                ('imported', models.BooleanField(default=False)),
                ('marked', models.BooleanField(default=False)),
                ('is_breakout', models.BooleanField(default=False)),
                ('accounting_categories', models.ManyToManyField(blank=True, related_name='budget_items', to='budgets.accountingcategory')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budgets.budget')),
            ],
            options={
                'ordering': ['date', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='budgets.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('source_type', models.CharField(choices=[('income', 'Income'), ('transfer', 'Transfer'), ('other', 'Other')], default='income', max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='budgets_sou_name_a10a17_idx'), models.Index(fields=['source_type'], name='budgets_sou_source__29766d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='budgets_mem_name_b5d7db_idx')],
            },
        ),
        migrations.CreateModel(
            name='CategoryVendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('irs_accounting_text', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='budgets.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItemRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('linked', 'Linked'), ('transfer', 'Transfer'), ('split_from', 'Split From'), ('correction', 'Correction')], default='linked', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('item1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='budgets.budgetitem')),
                ('item2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='budgets.budgetitem')),
            ],
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='budgets.category'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='category_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='budgets.categoryvendor'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='budgets.member'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakouts', to='budgets.budgetitem'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='budgets.source'),
        ),
        migrations.CreateModel(
            name='BudgetGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('file_name_string', models.CharField(blank=True, max_length=500)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='budgets.budgetgroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='categories',
            field=models.ManyToManyField(blank=True, to='budgets.category'),
        ),
        migrations.AddField(
            model_name='budget',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='budgets.budgetgroup'),
        ),
        migrations.AddField(
            model_name='budget',
            name='members',
            field=models.ManyToManyField(blank=True, to='budgets.member'),
        ),
        migrations.AddField(
            model_name='budget',
            name='sources',
            field=models.ManyToManyField(blank=True, to='budgets.source'),
        ),
        migrations.AddIndex(
            model_name='accountingcategory',
            index=models.Index(fields=['name'], name='budgets_acc_name_a7674a_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryvendor',
            index=models.Index(fields=['name'], name='budgets_cat_name_420ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryvendor',
            index=models.Index(fields=['category'], name='budgets_cat_categor_269c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='budgets_cat_name_a98b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetitemrelation',
            index=models.Index(fields=['item1', 'relation_type'], name='budgets_bud_item1_i_e6e530_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetitemrelation',
            index=models.Index(fields=['item2', 'relation_type'], name='budgets_bud_item2_i_fae266_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetitemrelation',
            unique_together={('item1', 'item2', 'relation_type')},
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['budget', 'date'], name='budgets_bud_budget__dc5dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['category'], name='budgets_bud_categor_068065_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['member'], name='budgets_bud_member__6306e3_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['source'], name='budgets_bud_source__a532fc_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['unique_id'], name='budgets_bud_unique__3f6f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['date', 'sequence_number'], name='budgets_bud_date_1262e2_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['imported'], name='budgets_bud_importe_f85585_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['is_breakout'], name='budgets_bud_is_brea_3864f5_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetgroup',
            index=models.Index(fields=['name'], name='budgets_bud_name_97d758_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetgroup',
            index=models.Index(fields=['parent'], name='budgets_bud_parent__243a03_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['name'], name='budgets_bud_name_1b0841_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['group', 'name'], name='budgets_bud_group_i_6bcd24_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['is_copy'], name='budgets_bud_is_copy_752bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['is_whatif'], name='budgets_bud_is_what_42b6b6_idx'),
        ),
    ]
