# Generated by Django 4.2.26 on 2025-12-10 04:08

from django.db import migrations, models


def migrate_categories_forward(apps, schema_editor):
    """Migrate existing single category to many-to-many"""
    BudgetItem = apps.get_model('budgets', 'BudgetItem')
    for item in BudgetItem.objects.all():
        if hasattr(item, 'category_id') and item.category_id:
            # Add the existing category to the new categories field
            item.categories.add(item.category_id)


def migrate_categories_backward(apps, schema_editor):
    """Migrate back: take first category from categories and set as category"""
    BudgetItem = apps.get_model('budgets', 'BudgetItem')
    for item in BudgetItem.objects.all():
        cats = item.categories.all()
        if cats:
            item.category = cats[0]
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        # Step 1: Add new many-to-many field
        migrations.AddField(
            model_name="budgetitem",
            name="categories",
            field=models.ManyToManyField(
                help_text="Categories for this transaction (can have multiple)",
                related_name="budget_items_new",
                to="budgets.category",
            ),
        ),
        # Step 2: Migrate data from old field to new field
        migrations.RunPython(migrate_categories_forward, migrate_categories_backward),
        # Step 3: Remove the index on old field
        migrations.RemoveIndex(
            model_name="budgetitem",
            name="budgets_bud_categor_068065_idx",
        ),
        # Step 4: Remove old single category field
        migrations.RemoveField(
            model_name="budgetitem",
            name="category",
        ),
        # Step 5: Rename related_name on new field to match the old one
        migrations.AlterField(
            model_name="budgetitem",
            name="categories",
            field=models.ManyToManyField(
                help_text="Categories for this transaction (can have multiple)",
                related_name="budget_items",
                to="budgets.category",
            ),
        ),
    ]
