# Generated by Django 4.2.26 on 2025-12-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0002_migrate_category_to_many_to_many"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetitem",
            name="import_source",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="budgetitem",
            name="reference_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
