# Generated by Django 4.2.26 on 2025-11-16 03:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('ofx', 'OFX/QFX'), ('quicken', 'Quicken'), ('excel', 'Excel'), ('json', 'JSON')], max_length=50)),
                ('items_imported', models.IntegerField(default=0)),
                ('duplicates_found', models.IntegerField(default=0)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='budgets.budget')),
            ],
            options={
                'ordering': ['-import_date'],
                'indexes': [models.Index(fields=['budget', '-import_date'], name='imports_imp_budget__31f10c_idx'), models.Index(fields=['file_type'], name='imports_imp_file_ty_808012_idx')],
            },
        ),
    ]
